### ISSUE TITLE
docker compose创建服务器问题

### ISSUE THREAD

**Issue by Don-James-shrinp** [Yorunina/No-Flesh-Within-Chest#160]
使用docker compose创建服务器端出现问题
### docker-compose.yml
`docker-compose.yml`如下所示
```yml
version: "3"

services:
  ftb-server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.19.2"
      FORGE_VERSION: "43.3.5"
      INIT_MEMORY: 4G
      MAX_MEMORY: 6G
      VIEW_DISTANCE: 10
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      WHITE_LIST: ""
      OPS: ""
      ONLINE_MODE: "FALSE"
      SERVER_NAME: "No Flesh Within Chest Server"
      MOTD: "No Flesh Within Chest Mod Server"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./No-Flesh-Within-Chest:/data
```

### 报错信息
```
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
RuOK Mod has class loading errors
§7java.lang.RuntimeException: Attempted to load class team/teampotato/ruok/forge/RuOKModForge for invalid dist DEDICATED_SERVER
]
at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:180) ~[fmlcore-1.19.2-43.3.5.jar%23440!/:?] {}
at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.3.5-universal.jar%23444!/:?] {re:classloading}
at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23439!/:?] {re:classloading,re:mixin,pl:mixin:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```

**Comment by Yorunina** [comment]
RuOKMod作为铷的附属，是一个客户端mod。如果你想开设服务器，建议你使用提供的官方forge端内的mod和kubejs文件作为参考。不然可能遇到很多的麻烦。

我已经将服务端上传到git release，你可以参考。（在上传之前，你需要去bilibili上的网盘中才能够下载）

**Comment by Don-James-shrinp** [comment]
> RuOKMod作为铷的附属，是一个客户端mod，服务器开设时需要将其删除。 如果你想开设服务器，建议你使用提供的官方forge端内的mod和kubejs文件作为参考。不然可能遇到很多的麻烦。
> 
> 我已经将服务端上传到git release，你可以参考。（在上传之前，你需要去bilibili上的网盘中才能够下载）

好的，感谢
